### ISSUE TITLE
Allow multiple Kubernetes namespaces

### ISSUE THREAD

**Issue by domeales-paloit** [cloudposse/terraform-aws-eks-fargate-profile#23]
## Describe the Feature

The module currently only accepts 1 Kubernetes namespace, it would be nice to allow multiple namespaces to avoid duplicated Fargate profiles for multiple namespaces.

## Expected Behavior

Currently only 1 namespace is accepted by variable `kubernetes_namespace`.

## Use Case

Currently designing a cluster that uses 1 Fargate profile for "system" type namespaces (Eg. kube-system, nginx-ingress, ...), and an additional Fargate profile for "workload" type namespaces.

## Describe Ideal Solution

The variable `kubernetes_namespace` could become a `list` of namespaces, which are applied using a `dynamic` configuration.

## Alternatives Considered

Duplicating a Fargate profile for each namespace (not very efficient or logical).

## Additional Context

-

**Comment by domeales-paloit** [comment]
That is true, but it only helps if your namespaces can be matched by the `*` - if not there is still a limitation.

**Comment by Nuru** [comment]
@domeales-paloit It is a limitation of Fargate Profiles that [each profile accepts only a single `namespace`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_fargate_profile#selector-configuration-block).

**Comment by domeales-paloit** [comment]
@Nuru The limitation is on a maximum of 5 selectors: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/eks/create-fargate-profile.html

The `selector` configuration block is a repeatable element in the Terraform configuration therefore it can be used multiple times to select multiple namespaces.

This would be easy to fix with a dynamic block statement.
