### ISSUE TITLE
Add support for coredns on fargate

### ISSUE THREAD

**Issue by nwsparks** [cloudposse/terraform-aws-eks-fargate-profile#8]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

By default EKS sets coredns to run on ec2. There is an operation required to get it to run on fargate as described here: https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html look for the "(Optional) Update CoreDNS" section.

## Use Case

Run entirely serverless

## Describe Ideal Solution

Perhaps an `enable_coredns_on_fargate` flag being set true patches CoreDNS to run on fargate?

**Comment by Nuru** [comment]
Closing as `wontfix` for the following reasons:

1. This request is beyond the scope of this module. This module provisions Fargate Profiles and a Fargate Pod Execution Role. It has nothing (directly) to do with CoreDNS or Add-Ons.
2. The requested operation is no longer required, as the CoreDNS Add-On can be configured directly to run on Fargate. See:

- [EKS Add-Ons Advanced Configuration](https://aws.amazon.com/blogs/containers/amazon-eks-add-ons-advanced-configuration/)

Specifically, you can set 

```
--configuration-values '{"computeType": "Fargate"}'
```

to get CoreDNS to run on Fargate.
